Changed tag from 2.7 to latest
When run docker-compose pull or up about 2.7 version it's occurring error about manifest not found for this image.
 I have made changed from 2.7 to "latest"   on 5 line.
Error message:
ERROR: manifest for ocsinventory/ocsinventory-docker-image:2.7 not found: manifest unknown: manifest unknown